### ISSUE TITLE
Multi OS syntax

### ISSUE THREAD

**Issue by SebCanet** [arrowhead-f/client-nodejs#2]
The code respects the UNIX syntax, I cannot launch nodemon on Windows.
Discussion: [https://shapeshed.com/writing-cross-platform-node/](https://shapeshed.com/writing-cross-platform-node/)

Many thanks.

**Comment by SebCanet** [comment]
It seems that you just need to add cross-env as dependency: [https://www.npmjs.com/package/cross-env](https://www.npmjs.com/package/cross-env)
And change all scripts by adding at the beginning "cross-env" like explained in usage. Still testing on...

**Comment by tsvetlin** [comment]
Resolved by #3
